layout_spectrum: 1
name: Lifes Images
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4881956
  lightness: 0.3207293
  saturation: 0.8282178
  rhythmicContrast: 0.4842758
  brandColors:
    - '#BDC6E0'
    - '#A36542'
    - '#41311F'
    - '#FFFFFF'
    - '#FFC69A'
typography_spectrum: 0.4443507
